"""deadlines

Revision ID: 8785775973a6
Revises: 35eacb0544c7
Create Date: 2026-09-26 22:41:42.829162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8785775973a6'
down_revision: Union[str, Sequence[str], None] = '35eacb0544c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=True),
    sa.Column('period_amount', sa.Integer(), nullable=False),
    sa.Column('period_unit', sa.String(length=4), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('service_kind', sa.String(length=30), nullable=False),
    sa.Column('count_start', sa.Date(), nullable=False),
    sa.Column('nominal_end', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('extended_over', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('basis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.String(length=100), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_case_id'), 'deadlines', ['case_id'], unique=False)
    op.create_index(op.f('ix_deadlines_deadline'), 'deadlines', ['deadline'], unique=False)
    op.create_index(op.f('ix_deadlines_document_id'), 'deadlines', ['document_id'], unique=False)
    op.create_index(op.f('ix_deadlines_status'), 'deadlines', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_status'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_document_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_deadline'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_case_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
